name = "helios-ledger-api"
main = "worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "helios-ledger"
database_id = "884d3be3-7389-49ea-aab3-7ae6720d4fa7"

[[routes]]
pattern = "ai.oooooooooo.se/api/*"
zone_name = "oooooooooo.se"
